[mypy]
strict = True
plugins = pydantic.mypy
files = $MYPY_CONFIG_FILE_DIR/app, $MYPY_CONFIG_FILE_DIR/tests
mypy_path = $MYPY_CONFIG_FILE_DIR/tests

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
